version: '3.8'

services:
  sakura-web:
    build: .
    container_name: sakura_app
    user: "0:0"
    restart: unless-stopped
    ports:
      - "5000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      # AICI SALVĂM BAZA DE DATE - Așa nu se pierde la reconstrucția containerului!
      - ./data:/usr/src/app/data